services:
  postgres:
    image: postgres:16
    container_name: airline-postgres
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  ingestion:
    build: .
    container_name: airline-ingestion

    env_file:
      - .env
    
    environment:
      POSTGRES_HOST: postgres

    depends_on:
      - postgres

volumes:
  postgres_data: